### ISSUE TITLE
Bug: Infinite profile loading

### ISSUE THREAD

**Issue by Shandeika** [CoffeSiberian/truck-tools#3]
When you start the app, profiles are loaded endlessly:
![image](https://github.com/user-attachments/assets/65f47ec7-ea6f-446c-9ae0-472b217d7ee9)

**Comment by CoffeSiberian** [comment]
This happens when the application does not detect any profile locally present in your “Documents” folder so remember to disable Steam Cloud from your profile

If you already have Steam Cloud disabled it may be because your “Documents” folder is located in a different place than the default (this happens when you change the location of the saves from the game startup settings) for this you can read the following answer in the SCS forum: https://forum.scssoft.com/viewtopic.php?p=1972326#p1972326
